# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        local_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads'
    filesystems:
        upload:
            adapter: local_adapter
            alias: League\Flysystem\FilesystemOperator
            mount: upload_fs
