#index:
#    path: /
#    controller: App\Controller\DefaultController::index
legacy_search:
  path: /search
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: 'search'
    permanent: true
    keepQueryParams: true
    keepRequestMethod: true
